version: '3.7'
services:
  mongo:
    image: mongo
    container_name: goboiler-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
    - goboiler-mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: ratingDB    
  mongo-express:
    image: mongo-express
    container_name: goboiler-mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
volumes: 
  goboiler-mongodata:
